export const REQUEST_STATE_NONE = 'REQUEST_STATE_NONE'
export const REQUEST_STATE_LOADING = 'REQUEST_STATE_LOADING'
export const REQUEST_STATE_LOADED = 'REQUEST_STATE_LOADED'
export const REQUEST_STATE_ERROR = 'REQUEST_STATE_ERROR'
